import '@storybook/addon-centered/react'
import '@storybook/addon-knobs/register'
import 'storybook-addon-styled-component-theme/dist/src/register'
import 'storybook-addon-jsx/register'
import '@storybook/addon-viewport/register'
import '@storybook/addon-notes/register'
import '@storybook/addon-actions/register'
